package(default_visibility = ["//im2txt:internal"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "inception_v4",
    srcs = ["inception_v4.py"],
    srcs_version = "PY2AND3",
)

